plugins { id 'java-library' }
evaluationDependsOn(':core')
dependencies { compileOnly files(rootProject.project(':core').tasks.named('drawSdkJar')) }
tasks.withType(JavaCompile).configureEach { options.release = 21 }
java { sourceCompatibility = JavaVersion.VERSION_21; targetCompatibility = JavaVersion.VERSION_21 }
