package com.wjz.worldsmith.core.model

import com.wjz.worldsmith.core.WorldsmithCore
import kotlinx.serialization.Serializable

@Serializable
enum class BiomeArchetypeRole {
    DEEP_OCEAN,
    OCEAN,
    BEACH,
    MOUNTAIN,
    HILL,
    LOWLAND,
}

/**
 * Where a biome sits along the land-shape axis.
 *
 * <p>Terrain height is driven by continentalness and erosion, so these presets
 * are useful when a prompt wants a familiar water/coast/highland split. They
 * are optional; raw climate boxes are equally first-class.
 */
@Serializable
enum class ReliefBand {
    DEEP_WATER,
    SHALLOW_WATER,
    COAST,
    PEAKS,
    HIGHLAND,
    FLATS,
}

@Serializable
enum class TemperatureBand {
    COLD,
    TEMPERATE,
    HOT,
}

@Serializable
enum class HumidityBand {
    ARID,
    HUMID,
}

/**
 * A concise way to place a biome: name bands instead of writing raw numbers.
 *
 * An empty list spans the whole axis. Listing several bands is allowed as long
 * as they are adjacent; a gap would make the resulting box quietly include the
 * band in between.
 */
@Serializable
data class ClimateSlot(
    val relief: ReliefBand,
    val temperature: List<TemperatureBand> = emptyList(),
    val humidity: List<HumidityBand> = emptyList(),
)

@Serializable
data class BiomeBehavior(
    val temperature: Float,
    val downfall: Float,
    val hasPrecipitation: Boolean,
)

@Serializable
data class SurfaceLayer(
    val material: MaterialSelector,
    val depth: Int,
)

/** Ordered from the exposed block downward, followed by [foundation]. */
@Serializable
data class SurfaceStack(
    val layers: List<SurfaceLayer>,
    val foundation: MaterialSelector,
)

@Serializable
data class SurfaceAltitude(
    val min: Int? = null,
    val max: Int? = null,
)

@Serializable
enum class SurfaceSlope {
    STEEP,
    GENTLE,
}

@Serializable
enum class SurfaceWater {
    ABOVE_WATER,
    UNDERWATER,
}

@Serializable
enum class SurfaceTemperature {
    FREEZING,
    NON_FREEZING,
}

/** Prompt-facing noise characters mapped to target-version noise parameters. */
@Serializable
enum class SurfaceNoise {
    PATCH,
    GRAVEL,
    CALCITE,
    SURFACE,
    SECONDARY,
    RUGGED,
}

@Serializable
data class SurfaceNoiseBand(
    val noise: SurfaceNoise,
    val min: Double,
    val max: Double,
)

/** Signals generated by Worldsmith's procedural hydrology compiler. */
@Serializable
enum class SurfaceHydrology {
    DRY_RIVERBED,
    WET_RIVERBED,
    RIVER_BANK,
    LAKEBED,
}

/** All declared fields are ANDed together. Null fields impose no condition. */
@Serializable
data class SurfaceConditions(
    val altitude: SurfaceAltitude? = null,
    val slope: SurfaceSlope? = null,
    val water: SurfaceWater? = null,
    val temperature: SurfaceTemperature? = null,
    val noise: SurfaceNoiseBand? = null,
    val hydrology: SurfaceHydrology? = null,
)

/** Earlier entries have higher priority; the first matching stack wins. */
@Serializable
data class SurfaceRuleDefinition(
    val id: String,
    val conditions: SurfaceConditions,
    val stack: SurfaceStack,
)

@Serializable
data class SurfaceDefinition(
    val base: SurfaceStack,
    val rules: List<SurfaceRuleDefinition>,
)

@Serializable
data class WaterFog(
    val color: String,
    val startDistance: Float,
    val endDistance: Float,
)

@Serializable
data class AmbientParticleSpec(
    val particle: String,
    val probability: Float,
)

/**
 * How a biome looks.
 *
 * <p>These fields land in two different places in Minecraft: the grass, foliage
 * and water colours become `BiomeSpecialEffects` overrides, while everything
 * fog, particle and sky related becomes an environment attribute. Authors do not
 * need to care, but the compiler does.
 */
@Serializable
data class BiomeEnvironment(
    val grassColor: String,
    val foliageColor: String,
    val waterColor: String,
    val skyColor: String,
    val fogColor: String,
    val fogEndDistance: Float = DEFAULT_FOG_END_DISTANCE,
    val waterFog: WaterFog? = null,
    val ambientParticles: List<AmbientParticleSpec> = emptyList(),
) {
    companion object {
        const val DEFAULT_FOG_END_DISTANCE: Float = 192.0f
    }
}

/**
 * Adjustments to the tag set the archetype already implies.
 *
 * <p>[remove] subtracts from those defaults. It cannot take a biome out of a
 * vanilla tag it was never in, because a Worldsmith biome only joins a tag when
 * this pack puts it there.
 */
@Serializable
data class BiomeTagOverrides(
    val add: List<String> = emptyList(),
    val remove: List<String> = emptyList(),
)

/** A reference to a feature in the pack's feature library. */
@Serializable
data class BiomeFeatureRef(
    val feature: String,
    val density: Double? = null,
)

@Serializable
data class BiomeDefinition(
    val id: String,
    val displayName: String,
    val archetype: BiomeArchetypeRole,
    val slot: ClimateSlot? = null,
    val climate: ClimateBox? = null,
    val behavior: BiomeBehavior,
    val surface: SurfaceDefinition,
    val environment: BiomeEnvironment,
    val tags: BiomeTagOverrides = BiomeTagOverrides(),
    val features: List<BiomeFeatureRef> = emptyList(),
)

@Serializable
data class BiomePlan(
    val schemaVersion: Int = WorldsmithCore.BLUEPRINT_SCHEMA_VERSION,
    val biomes: List<BiomeDefinition>,
)
