package com.wjz.worldsmith.core.model

import com.wjz.worldsmith.core.WorldsmithCore
import kotlinx.serialization.Serializable

@Serializable
enum class BiomeArchetypeRole {
    DEEP_OCEAN,
    OCEAN,
    BEACH,
    MOUNTAIN,
    HILL,
    LOWLAND,
}

/**
 * Where a biome sits along the land-shape axis.
 *
 * <p>Terrain height is driven by continentalness and erosion, so these presets
 * are useful when a prompt wants a familiar water/coast/highland split. They
 * are optional; raw climate boxes are equally first-class.
 */
@Serializable
enum class ReliefBand {
    DEEP_WATER,
    SHALLOW_WATER,
    COAST,
    PEAKS,
    HIGHLAND,
    FLATS,
}

@Serializable
enum class TemperatureBand {
    COLD,
    TEMPERATE,
    HOT,
}

@Serializable
enum class HumidityBand {
    ARID,
    HUMID,
}

/**
 * A concise way to place a biome: name bands instead of writing raw numbers.
 *
 * An empty list spans the whole axis. Listing several bands is allowed as long
 * as they are adjacent; a gap would make the resulting box quietly include the
 * band in between.
 */
@Serializable
data class ClimateSlot(
    val relief: ReliefBand,
    val temperature: List<TemperatureBand> = emptyList(),
    val humidity: List<HumidityBand> = emptyList(),
)

@Serializable
data class BiomeBehavior(
    val temperature: Float,
    val downfall: Float,
    val hasPrecipitation: Boolean,
)

@Serializable
data class SurfaceLayer(
    val material: MaterialSelector,
    val depth: Int,
)

/** Ordered from the exposed block downward, followed by [foundation]. */
@Serializable
data class SurfaceStack(
    val layers: List<SurfaceLayer>,
    val foundation: MaterialSelector,
)

@Serializable
data class SurfaceAltitude(
    val min: Int? = null,
    val max: Int? = null,
)

@Serializable
enum class SurfaceSlope {
    STEEP,
    GENTLE,
}

@Serializable
enum class SurfaceWater {
    ABOVE_WATER,
    UNDERWATER,
}

@Serializable
enum class SurfaceTemperature {
    FREEZING,
    NON_FREEZING,
}

/** Prompt-facing noise characters mapped to target-version noise parameters. */
@Serializable
enum class SurfaceNoise {
    PATCH,
    GRAVEL,
    CALCITE,
    SURFACE,
    SECONDARY,
    RUGGED,
}

@Serializable
data class SurfaceNoiseBand(
    val noise: SurfaceNoise,
    val min: Double,
    val max: Double,
)

/**
 * A ring of one anchor's influence, as a fraction of its radius.
 *
 * <p>Bands let a landmark wear different materials at its summit, its flanks
 * and its foot, which is what stops it reading as the surrounding ground
 * pushed upward.
 */
@Serializable
data class SurfaceAnchorBand(
    val anchor: String,
    val min: Double = 0.0,
    val max: Double = 1.0,
)

/** Signals generated by Worldsmith's procedural hydrology compiler. */
@Serializable
enum class SurfaceHydrology {
    DRY_RIVERBED,
    WET_RIVERBED,
    RIVER_BANK,
    LAKEBED,
}

/** All declared fields are ANDed together. Null fields impose no condition. */
@Serializable
data class SurfaceConditions(
    val altitude: SurfaceAltitude? = null,
    val slope: SurfaceSlope? = null,
    val water: SurfaceWater? = null,
    val temperature: SurfaceTemperature? = null,
    val noise: SurfaceNoiseBand? = null,
    val hydrology: SurfaceHydrology? = null,
    val anchor: SurfaceAnchorBand? = null,
)

/** Earlier entries have higher priority; the first matching stack wins. */
@Serializable
data class SurfaceRuleDefinition(
    val id: String,
    val conditions: SurfaceConditions,
    val stack: SurfaceStack,
)

@Serializable
data class SurfaceDefinition(
    val base: SurfaceStack,
    val rules: List<SurfaceRuleDefinition>,
)

@Serializable
data class WaterFog(
    val color: String,
    val startDistance: Float,
    val endDistance: Float,
)

/**
 * Colours Minecraft applies to blocks rather than to the air.
 *
 * <p>These are the only part of a biome's look that is not an environment
 * attribute: they become `BiomeSpecialEffects` overrides, so they neither
 * interpolate across a border nor respond to weather.
 */
@Serializable
data class BiomeTint(
    val grass: String,
    val foliage: String,
    val water: String,
)

/**
 * How far the player can see, and in what colour.
 *
 * <p>[skyEndDistance] and [cloudEndDistance] are separate on purpose: a world
 * can be clear at ground level and still have a sky that fades to nothing.
 */
@Serializable
data class BiomeFog(
    val color: String,
    val startDistance: Float = 0.0f,
    val endDistance: Float = DEFAULT_END_DISTANCE,
    val skyEndDistance: Float? = null,
    val cloudEndDistance: Float? = null,
    val water: WaterFog? = null,
) {
    companion object {
        const val DEFAULT_END_DISTANCE: Float = 192.0f
    }
}

/**
 * What is overhead.
 *
 * <p>Cloud and sunrise colours carry alpha, so they are `#AARRGGBB` while every
 * other colour in a pack is `#RRGGBB`. A fully transparent cloud colour is how
 * a world gets no clouds at all.
 */
@Serializable
data class BiomeSky(
    val color: String,
    val cloudColor: String? = null,
    val cloudHeight: Float? = null,
    val sunriseSunsetColor: String? = null,
    val starBrightness: Float? = null,
)

/**
 * The colour and strength of light itself.
 *
 * <p>This group is what makes a place feel wrong rather than merely look
 * different: [blockTint] recolours torchlight, [skyFactor] decides how much of
 * the sky's light actually arrives, and [ambientColor] sets the floor that
 * unlit corners never fall below.
 */
@Serializable
data class BiomeLight(
    val skyColor: String? = null,
    val ambientColor: String? = null,
    val blockTint: String? = null,
    val skyFactor: Float? = null,
)

@Serializable
data class AmbientParticleSpec(
    val particle: String,
    val probability: Float,
)

/**
 * How a biome looks.
 *
 * <p>Grouped by what a person would change together rather than by where the
 * value lands in Minecraft. [tint] becomes `BiomeSpecialEffects`; everything
 * else becomes an environment attribute, which means it interpolates across
 * biome borders and stacks with the day-night and weather layers instead of
 * replacing them.
 *
 * <p>Every optional field left null keeps Minecraft's own value, so a pack only
 * describes what it wants to be different.
 */
@Serializable
data class BiomeEnvironment(
    val tint: BiomeTint,
    val fog: BiomeFog,
    val sky: BiomeSky,
    val light: BiomeLight = BiomeLight(),
    val ambientParticles: List<AmbientParticleSpec> = emptyList(),
)

/**
 * Adjustments to the tag set the archetype already implies.
 *
 * <p>[remove] subtracts from those defaults. It cannot take a biome out of a
 * vanilla tag it was never in, because a Worldsmith biome only joins a tag when
 * this pack puts it there.
 */
@Serializable
data class BiomeTagOverrides(
    val add: List<String> = emptyList(),
    val remove: List<String> = emptyList(),
)

/** A reference to a feature in the pack's feature library. */
@Serializable
data class BiomeFeatureRef(
    val feature: String,
    val density: Double? = null,
)

@Serializable
data class BiomeDefinition(
    val id: String,
    val displayName: String,
    val archetype: BiomeArchetypeRole,
    val slot: ClimateSlot? = null,
    val climate: ClimateBox? = null,
    val behavior: BiomeBehavior,
    val surface: SurfaceDefinition,
    val environment: BiomeEnvironment,
    val tags: BiomeTagOverrides = BiomeTagOverrides(),
    val features: List<BiomeFeatureRef> = emptyList(),
)

@Serializable
data class BiomePlan(
    val schemaVersion: Int = WorldsmithCore.BLUEPRINT_SCHEMA_VERSION,
    val biomes: List<BiomeDefinition>,
)
