"""Regenerates core/src/main/java/com/wjz/worldsmith/core/draw/DrawPreviewColours.java.

Usage: python tools/generate_preview_colours.py <minecraft client jar>

For every blockstate, follows the first variant's model through its parents to
the texture a viewer mostly sees (side, all, texture, pane, cross ... top) and
averages its non-transparent pixels, first frame only for animated textures.
Blocks whose model is biome-tinted are left out: their textures are grey.
"""
import json, sys, zipfile, io, pathlib
from PIL import Image
jar = zipfile.ZipFile(sys.argv[1])
names = set(jar.namelist())
def load(path):
    return json.loads(jar.read(path)) if path in names else None
def model_path(ref):
    ref = ref.split(':', 1)[-1]
    return 'assets/minecraft/models/' + ref + '.json'
cache = {}
def resolve(ref):
    """Merged textures and whether any element in the chain is tinted."""
    if ref in cache: return cache[ref]
    m = load(model_path(ref)) or {}
    textures, tinted, elements = {}, False, None
    if 'parent' in m:
        pt, ptint, pel = resolve(m['parent'])
        textures.update(pt); tinted = ptint; elements = pel
    textures.update(m.get('textures', {}))
    if 'elements' in m: elements = m['elements']; tinted = any('tintindex' in f for e in m['elements'] for f in e.get('faces', {}).values())
    cache[ref] = (textures, tinted, elements)
    return cache[ref]
def first_model(state):
    if 'variants' in state:
        v = next(iter(state['variants'].values()))
    else:
        v = state['multipart'][0]['apply']
    return (v[0] if isinstance(v, list) else v)['model']
PRIORITY = ['side', 'all', 'texture', 'pane', 'cross', 'plant', 'crop', 'bottom', 'front', 'wall', 'end', 'top', 'particle']
def pick(textures):
    def deref(v, depth=0):
        if isinstance(v, dict): v = v.get('sprite', '')
        while v.startswith('#') and depth < 16:
            v = textures.get(v[1:], ''); depth += 1
            if isinstance(v, dict): v = v.get('sprite', '')
        return v if v and not v.startswith('#') else None
    for key in PRIORITY:
        if key in textures and deref(textures[key]): return deref(textures[key])
    for v in textures.values():
        if deref(v): return deref(v)
    return None
avg_cache = {}
def average(tex):
    if tex in avg_cache: return avg_cache[tex]
    path = 'assets/minecraft/textures/' + tex.split(':', 1)[-1] + '.png'
    if path not in names: avg_cache[tex] = None; return None
    img = Image.open(io.BytesIO(jar.read(path))).convert('RGBA')
    w, h = img.size
    if h > w: img = img.crop((0, 0, w, w))
    r = g = b = n = 0
    for (pr, pg, pb, pa) in img.get_flattened_data():
        if pa == 0: continue
        r += pr * pa; g += pg * pa; b += pb * pa; n += pa
    avg_cache[tex] = None if n == 0 else (round(r / n), round(g / n), round(b / n))
    return avg_cache[tex]
out, tinted_ids, missing = [], [], []
for path in sorted(names):
    if not (path.startswith('assets/minecraft/blockstates/') and path.endswith('.json')): continue
    bid = path.rsplit('/', 1)[1][:-5]
    try: model = first_model(load(path))
    except Exception: missing.append(bid); continue
    textures, tinted, _ = resolve(model)
    tex = pick(textures)
    if tinted: tinted_ids.append(bid); continue
    rgb = average(tex) if tex else None
    if rgb is None: missing.append(bid); continue
    out.append('%s:%02x%02x%02x' % (bid, *rgb))
print(len(out), 'coloured;', len(tinted_ids), 'tinted skipped;', len(missing), 'without texture', file=sys.stderr)
print('tinted:', ' '.join(tinted_ids[:40]), file=sys.stderr)
print('missing:', ' '.join(missing[:40]), file=sys.stderr)

entries = ';'.join(out)
chunks = [entries[i:i + 96] for i in range(0, len(entries), 96)]
body = '\n\t\t+ '.join('"%s"' % c for c in chunks)
java = f"""package com.wjz.worldsmith.core.draw;

import java.util.HashMap;
import java.util.Map;

/**
 * Average colours of vanilla blocks, measured from the Minecraft client's own
 * textures: for each block, the texture its first model mostly shows, averaged
 * over its opaque pixels. Biome-tinted blocks are absent because their textures
 * are grey until tinted. Generated by tools/generate_preview_colours.py; rerun it
 * when the target Minecraft version changes.
 */
final class DrawPreviewColours {{
	private static final String DATA = {body};
	private static final Map<String, Integer> AVERAGE = new HashMap<>();
	static {{
		for (String entry : DATA.split(";")) {{
			int colon = entry.indexOf(':');
			AVERAGE.put("minecraft:" + entry.substring(0, colon), Integer.parseInt(entry.substring(colon + 1), 16));
		}}
	}}
	private DrawPreviewColours() {{}}

	/** The measured average RGB of a vanilla block id, or null when none was measured. */
	static Integer average(String id) {{ return AVERAGE.get(id); }}
}}
"""
target = pathlib.Path(__file__).resolve().parent.parent / 'core/src/main/java/com/wjz/worldsmith/core/draw/DrawPreviewColours.java'
target.write_text(java, newline='\n')
