package com.wjz.worldsmith.core.content

import kotlinx.serialization.Serializable

/** Bounded aliases for existing vanilla events; no downloaded or generated audio. */
@Serializable
enum class CreatureSound(val eventId: String?) {
    SILENT(null),
    COW_AMBIENT("minecraft:entity.cow.ambient"),
    COW_HURT("minecraft:entity.cow.hurt"),
    COW_DEATH("minecraft:entity.cow.death"),
    SHEEP_AMBIENT("minecraft:entity.sheep.ambient"),
    SHEEP_HURT("minecraft:entity.sheep.hurt"),
    SHEEP_DEATH("minecraft:entity.sheep.death"),
    PIG_AMBIENT("minecraft:entity.pig.ambient"),
    PIG_HURT("minecraft:entity.pig.hurt"),
    PIG_DEATH("minecraft:entity.pig.death"),
    CHICKEN_AMBIENT("minecraft:entity.chicken.ambient"),
    CHICKEN_HURT("minecraft:entity.chicken.hurt"),
    CHICKEN_DEATH("minecraft:entity.chicken.death"),
    RABBIT_AMBIENT("minecraft:entity.rabbit.ambient"),
    RABBIT_HURT("minecraft:entity.rabbit.hurt"),
    RABBIT_DEATH("minecraft:entity.rabbit.death"),
    RABBIT_ATTACK("minecraft:entity.rabbit.attack"),
    WOLF_AMBIENT("minecraft:entity.wolf.ambient"),
    WOLF_HURT("minecraft:entity.wolf.hurt"),
    WOLF_DEATH("minecraft:entity.wolf.death"),
    WOLF_GROWL("minecraft:entity.wolf.growl"),
    FOX_AMBIENT("minecraft:entity.fox.ambient"),
    FOX_HURT("minecraft:entity.fox.hurt"),
    FOX_DEATH("minecraft:entity.fox.death"),
    FOX_BITE("minecraft:entity.fox.bite"),
    CAT_AMBIENT("minecraft:entity.cat.ambient"),
    CAT_HURT("minecraft:entity.cat.hurt"),
    CAT_DEATH("minecraft:entity.cat.death"),
    CAT_HISS("minecraft:entity.cat.hiss"),
    CAT_PURR("minecraft:entity.cat.purr"),
    SPIDER_AMBIENT("minecraft:entity.spider.ambient"),
    SPIDER_HURT("minecraft:entity.spider.hurt"),
    SPIDER_DEATH("minecraft:entity.spider.death"),
    ZOMBIE_AMBIENT("minecraft:entity.zombie.ambient"),
    ZOMBIE_HURT("minecraft:entity.zombie.hurt"),
    ZOMBIE_DEATH("minecraft:entity.zombie.death"),
    SKELETON_AMBIENT("minecraft:entity.skeleton.ambient"),
    SKELETON_HURT("minecraft:entity.skeleton.hurt"),
    SKELETON_DEATH("minecraft:entity.skeleton.death"),
    SKELETON_SHOOT("minecraft:entity.skeleton.shoot"),
    ENDERMAN_AMBIENT("minecraft:entity.enderman.ambient"),
    ENDERMAN_HURT("minecraft:entity.enderman.hurt"),
    ENDERMAN_DEATH("minecraft:entity.enderman.death"),
    ENDERMAN_SCREAM("minecraft:entity.enderman.scream"),
    ENDERMAN_STARE("minecraft:entity.enderman.stare"),
    BLAZE_AMBIENT("minecraft:entity.blaze.ambient"),
    BLAZE_HURT("minecraft:entity.blaze.hurt"),
    BLAZE_DEATH("minecraft:entity.blaze.death"),
    BLAZE_SHOOT("minecraft:entity.blaze.shoot"),
    GHAST_AMBIENT("minecraft:entity.ghast.ambient"),
    GHAST_HURT("minecraft:entity.ghast.hurt"),
    GHAST_DEATH("minecraft:entity.ghast.death"),
    GHAST_WARN("minecraft:entity.ghast.warn"),
    SLIME_SQUISH("minecraft:entity.slime.squish"),
    SLIME_HURT("minecraft:entity.slime.hurt"),
    SLIME_DEATH("minecraft:entity.slime.death"),
    SLIME_ATTACK("minecraft:entity.slime.attack"),
    IRON_GOLEM_HURT("minecraft:entity.iron_golem.hurt"),
    IRON_GOLEM_DEATH("minecraft:entity.iron_golem.death"),
    IRON_GOLEM_ATTACK("minecraft:entity.iron_golem.attack"),
    RAVAGER_AMBIENT("minecraft:entity.ravager.ambient"),
    RAVAGER_HURT("minecraft:entity.ravager.hurt"),
    RAVAGER_DEATH("minecraft:entity.ravager.death"),
    RAVAGER_ATTACK("minecraft:entity.ravager.attack"),
    RAVAGER_ROAR("minecraft:entity.ravager.roar"),
    POLAR_BEAR_AMBIENT("minecraft:entity.polar_bear.ambient"),
    POLAR_BEAR_HURT("minecraft:entity.polar_bear.hurt"),
    POLAR_BEAR_DEATH("minecraft:entity.polar_bear.death"),
    POLAR_BEAR_WARNING("minecraft:entity.polar_bear.warning");
}

@Serializable enum class CreatureVoice { COW, SHEEP, PIG, CHICKEN, RABBIT, WOLF, FOX, CAT, SPIDER, ZOMBIE, SKELETON, ENDERMAN, BLAZE, GHAST, SLIME, IRON_GOLEM, RAVAGER, POLAR_BEAR }

enum class CreatureSoundRole { AMBIENT, HURT, DEATH, ATTACK }
